// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpgqmwexjvquhtvsapyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZ3Ftd2V4anZxdWh0dnNhcHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQwNzYsImV4cCI6MjA3MzEwMDA3Nn0.GolCRWruDJ4IGckK-XLuyUTTh-r2KN7BrRwWNnz4ZCA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});